export const DEFAULT_WIN_MULTIPLIER = 1.1
export const DEFAULT_TOKEN_AMOUNT = 300
export const SPONSORSHIP_TOKEN_GAIN = 100
export const SPONSORSHIP_TOKEN_GAIN_NEW_USER = 200

export const DAILY_TOKEN_GAIN = 5
export const DAILY_TOKEN_GAIN_AFTER_7_DAYS = 10
export const DAILY_TOKEN_GAIN_AFTER_14_DAYS = 15
export const DAILY_TOKEN_GAIN_AFTER_30_DAYS = 20
export const DAILY_TOKEN_GAIN_FREQUENCY_AFTER_30_DAYS = 3
